### ISSUE TITLE
The text incorrectly refers to a play button for REPL.

### ISSUE THREAD

**Issue by Zio-4** [learn-co-curriculum/phase-0-pac-1-expressions-in-js#1]
"If you click the play button above the equation, you should see 20 appear in the bottom box." Maybe REPL used to have a play button but it is now a run button. Not major but could be fixed for clarity.

**Comment by bal360** [comment]
Thank you for spotting this issue and providing feedback.

When the browser window is minimized to a certain point the word `Run` disappears from the Replit button and only the play symbol (▶) remains. So we have updated the material to be a bit more explicit but have opted against using the word `Run` because that will not be universally applicable.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
